name: xMedika
favicon: null
layout_spectrum: 0
typography_spectrum: 0.56342
title: Tecnologia para Saúde
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eef1f2'
    - '#23282d'
    - '#ff0000'
    - '#ff8000'
    - '#0f9d58'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
