name: xMedika
favicon: null
layout_spectrum: 0
typography_spectrum: 0.56342
title: Tecnologia para Saúde
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#bcbcbc'
    - '#005fac'
    - '#0b0b0b'
    - '#a01811'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
